services:
  afrimillions:
    build: .
    container_name: afrimillions
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./database:/app/database
    environment:
      - DATA_FOLDER=/app/data
      - DB_PATH=/app/database/notified_users.db
      - TZ=Africa/Lagos
